version: '2.1'

services:
  registry:
    image: 'registry:2'

  engine:
      image: 'docker:${TEST_ENGINE_VERSION:-stable-dind}'
      privileged: true
      command: ['--insecure-registry=registry:5000']
      environment:
        - DOCKER_TLS_CERTDIR=

  notary-server:
      build:
        context: ./testdata
        dockerfile: Dockerfile.notary-server
      ports:
        - 4443:4443
      command: ['notary-server', '-config=/fixtures/notary-config.json']
