
FROM    golang:1.8-alpine

RUN     apk add -U git make

RUN     go get github.com/LK4D4/vndr && \
        cp /go/bin/vndr /usr/bin && \
        rm -rf /go/src/* /go/pkg/* /go/bin/*

RUN     go get github.com/mitchellh/gox && \
        cp /go/bin/gox /usr/bin && \
        rm -rf /go/src/* /go/pkg/* /go/bin/*

ENV     CGO_ENABLED=0
WORKDIR /go/src/github.com/docker/cli
CMD     sh
