FROM    koalaman/shellcheck-alpine:v0.4.6
RUN     apk add --no-cache bash make
WORKDIR /go/src/github.com/docker/cli
ENV     DISABLE_WARN_OUTSIDE_CONTAINER=1
ENTRYPOINT [""]
CMD     ["/bin/sh"]
COPY    . .
