#!/bin/sh
set -e

case "$1" in
	configure)
		if [ -z "$2" ]; then
			if ! getent group docker > /dev/null; then
				groupadd --system docker
			fi
                        # TODO Needs upgrade vs. install logic handling here
                        if ctr --namespace docker container info dockerd 2&>1  > /dev/null ; then
                            docker engine init
                        fi
		fi
		;;
	abort-*)
		# How'd we get here??
		exit 1
		;;
	*)
		;;
esac

#DEBHELPER#
