#!/usr/bin/env bash
set -e

# Maintain an array of files to shellcheck not the best solution but will do for the time being
FILES=()
FILES+=("contrib/completion/bash/docker")
FILES+=("scripts/validate/shellcheck")

for f in "${FILES[@]}"; do
    shellcheck "$f"
done
