#!/usr/bin/env sh

arch="$(uname -m)"
img="unknown"

if [ "$arch" = "x86_64" ]; then
    img="alpine"
elif [ "$arch" = "armv7l" ]; then
    img="arm32v6/alpine"
elif [ "$arch" = "s390x" ]; then
    img="s390x/alpine"
elif [ "$arch" = "aarch64" ]; then
    img="arm64v8/alpine"
elif [ "$arch" = "ppc64le" ]; then
    img="ppc64le/alpine"
else
    echo "Architecture $(arch) not supported"
    exit 1;
fi

echo "$img"
